src/Entity/Partida.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PartidaRepository")
 */
class Partida
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="text")
     */
    private $descricao;

    /**
     * @var integer
     * @ORM\Column(type="integer")
     */
    private $placar_visitante;

    /**
     * @var integer
     * @ORM\Column(type="integer")
     */
    private $placar_casa;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    private $data_partida;

    /**
     * @var Campeonato
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Campeonato"))
     */
    private $campeonato;

    /**
     * @var Time
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Time", inversedBy="partidas_casa")
     */
    private $time_casa;

    /**
     * @var Time
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Time", inversedBy="partidas_visitante")
     */
    private $time_visitante;

    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getDescricao(): string
    {
        return $this->descricao;
    }

    /**
     * @param string $descricao
     * @return Partida
     */
    public function setDescricao(string $descricao): Partida
    {
        $this->descricao = $descricao;
        return $this;
    }

    /**
     * @return int
     */
    public function getPlacarVisitante(): int
    {
        return $this->placar_visitante;
    }

    /**
     * @param int $placar_visitante
     * @return Partida
     */
    public function setPlacarVisitante(int $placar_visitante): Partida
    {
        $this->placar_visitante = $placar_visitante;
        return $this;
    }

    /**
     * @return int
     */
    public function getPlacarCasa(): int
    {
        return $this->placar_casa;
    }

    /**
     * @param int $placar_casa
     * @return Partida
     */
    public function setPlacarCasa(int $placar_casa): Partida
    {
        $this->placar_casa = $placar_casa;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDataPartida(): \DateTime
    {
        return $this->data_partida;
    }

    /**
     * @param \DateTime $data_partida
     * @return Partida
     */
    public function setDataPartida(\DateTime $data_partida): Partida
    {
        $this->data_partida = $data_partida;
        return $this;
    }

    /**
     * @return Campeonato
     */
    public function getCampeonato(): Campeonato
    {
        return $this->campeonato;
    }

    /**
     * @param Campeonato $campeonato
     * @return Partida
     */
    public function setCampeonato(Campeonato $campeonato): Partida
    {
        $this->campeonato = $campeonato;
        return $this;
    }

    /**
     * @return Time
     */
    public function getTimeCasa(): Time
    {
        return $this->time_casa;
    }

    /**
     * @param Time $time_casa
     * @return Partida
     */
    public function setTimeCasa(Time $time_casa): Partida
    {
        $this->time_casa = $time_casa;
        return $this;
    }

    /**
     * @return Time
     */
    public function getTimeVisitante(): Time
    {
        return $this->time_visitante;
    }

    /**
     * @param Time $time_visitante
     * @return Partida
     */
    public function setTimeVisitante(Time $time_visitante): Partida
    {
        $this->time_visitante = $time_visitante;
        return $this;
    }





}

src/Controller/PartidasController.php
<?php

namespace App\Controller;

use App\Entity\Partida;
use App\Entity\Time;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\VarDumper\VarDumper;

class PartidasController extends Controller
{
    protected $em;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->em = $entityManager;
    }

    /**
     * @Route("/partidas", name="partidas")
     * @Template("partidas/index.html.twig")
     * @return array
     */
    public function index()
    {
        $partidas = $this->em->getRepository(Partida::class)
            ->getPartidasPorData();
//        VarDumper::dump($partidas);
//        exit;
        return [
            'partidas' => $partidas
        ];
    }

    /**
     * @param Time $time
     * @Route("/partidas/listar-por-time/{id}", name="listar-partidas")
     * @Template("partidas/listar-por-time.html.twig")
     * @return array
     */
    public function partidasPorTimes(Time $time)
    {
        $partidas = $this->em->getRepository(Partida::class)
            ->getPartidasPorTime($time);

        return [
            'partidas' => $partidas,
            'time' => $time
        ];
    }
}

templates/partidas/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1 class="display-3">Partidas</h1>
<table class="table table-striped table-hover center">
    <thead>
    <tr>
        <th>Descrição</th>
        <th>Placar Visitante</th>
        <th>Placar Casa</th>
        <th>Data da Partida</th>
        <th>Campeonato</th>
    </tr>
    </thead>
    <tbody>
    {% for partida in partidas %}
    <tr>
        <td>{{ partida.descricao }}</td>
        <td>{{ partida.placarVisitante }}</td>
        <td>{{ partida.placarCasa }}</td>
        <td>{{ partida.dataPartida|date("d/m/Y H:i") }}</td>
        <td>{{  partida.campeonato.nome }}</td>
    </tr>
    {% endfor %}
    </tbody>

</table>

{% endblock %}

{% block title %}
    {% for partida in partidas %}
    Listando Partidas de {{ partida.dataPartida|date("d/m/Y H:i") }}"
    {% endfor %}
{% endblock %}

templates/partidas/listar-por-time.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="display-3">Partidas de {{ time.nome }}</h1>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Campeonato</th>
            <th>Adversário</th>
            <th>Placar</th>
            <th>Local</th>
            <th>Data</th>
        </tr>
        </thead>
        <tbody>
        {% for partida in partidas %}
            <tr>
                <td>{{ partida.campeonato.nome }}</td>
                <td>
                    {% if time.id == partida.timeCasa.id %}
                        {{ partida.timeVisitante.nome }}
                    {% else %}
                        {{ partida.campeonato.nome }}
                    {% endif %}
                </td>
                <td>
                    {% if time.id == partida.timeCasa.id %}
                        {{ partida.placarCasa }} x {{ partida.placarVisitante }}
                    {% else %}
                        {{ partida.placarVisitante }} x {{ partida.placarCasa }}
                    {% endif %}
                </td>
                <td>
                    {% if time.id == partida.timeCasa.id %}
                        Time da Casa
                    {% else %}
                        Time
                    {% endif %}
                </td>
                <td>{{ partida.dataPartida|date("d/m/Y H:i") }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block title %}
    Listando Partidas de {{ time.nome }}"
{% endblock %}